### ISSUE TITLE
Add delete question option

### ISSUE THREAD

**Issue by liornoy** [beyond-io/shlifim#144]
Users should be able to delete their own questions from the display-question page.
The delete button should be visible only to the question author, and after clicking it, it should open another window asking the user if he/she is sure.

**Comment by liornoy** [comment]
Delete button looks from display question page: 
![image](https://user-images.githubusercontent.com/40122521/120349591-e7bbd980-c306-11eb-87fc-ef5d51513cfa.png)

Delete conformation page:
![image](https://user-images.githubusercontent.com/40122521/120349673-f904e600-c306-11eb-80d6-83f1ccae75e8.png)

Successfull operation message after delete:
![image](https://user-images.githubusercontent.com/40122521/120349815-189c0e80-c307-11eb-8307-d1c6d46c3bf4.png)

**Comment by avivz450** [comment]
I liked the idea, but I think that a pop-up will be better instead of this page :
![image](https://user-images.githubusercontent.com/50836486/120358734-851b0b80-c30f-11eb-93ad-8b032d2f11ae.png)

**Comment by danitLevi** [comment]
> I liked the idea, but I think that a pop-up will be better instead of this page :
> 
> ![image](https://user-images.githubusercontent.com/50836486/120358734-851b0b80-c30f-11eb-93ad-8b032d2f11ae.png)
> 
> @liornoy

I agreee

**Comment by danitLevi** [comment]
> I liked the idea, but I think that a pop-up will be better instead of this page :
> 
> ![image](https://user-images.githubusercontent.com/50836486/120358734-851b0b80-c30f-11eb-93ad-8b032d2f11ae.png)
> 
> @liornoy

I agree with Aviv

**Comment by liornoy** [comment]
Ok Ill change it

**Comment by avivz450** [comment]
Great :)
Can you please send me a review request once you finished?

**Comment by liornoy** [comment]
I'm using the javascript "confirm" function here.
There is an option to build a pop-up HTML component with CSS logic, but it didn't work out for me.
Neither adding the trash icon to the "delete" button, which is an input tag now.
![image](https://user-images.githubusercontent.com/40122521/120883763-b0d81300-c5e7-11eb-9670-f82ccc410c0f.png)
This can and should be upgrade in a future PR
