### ISSUE TITLE
Post question allow sub-subject not matching subject

### ISSUE THREAD

**Issue by liornoy** [beyond-io/shlifim#156]

**Comment by liornoy** [comment]
@avivz450 About this bug, (which I'm also working on) I came to the conclusion we should override the is_valid method of the QuestionForm, and check there if the sub_subject matches the subject. One thing though is that I need to add a way to distinguish between different is_valid errors. because as for now, when is_valid fails it prints an error message about the page number limit.

**Comment by avivz450** [comment]
Maybe you should implement the method `clean_sub_subject` in `home/forms.py` and check there if there is a good match.
if there isn't, you can raise `ValidationError`.
You can see `clean_email` method for an example in the SignUpForm - https://github.com/avivz450/A-GBusinessesPromotions/blob/main/App/forms.py

**Comment by liornoy** [comment]
Good idea thanks!
