### ISSUE TITLE
Clicking the C# tag cause 'No Tag matches the given query' error

### ISSUE THREAD

**Issue by liornoy** [beyond-io/shlifim#171]

**Comment by liornoy** [comment]
I figured out that when you enter the character '#' to the URL, it gets filtered so the app looks for tag = c which doesn't exist.
Maybe we should prevent the chars other than Alphanumeric (a-z, A-Z, 0-9) letters in the tags.
@avivz450  what do you think?

**Comment by avivz450** [comment]
I think that's a good idea. 
I checked also some other platforms, like Instagram, and I saw that also there chars like '#','!','@' and more don't exist in the tags
