### ISSUE TITLE
Create Answers Model and Migrations 

### ISSUE THREAD

**Issue by idokk1** [beyond-io/shlifim#18]
Create a DB table for Answers following the table in the ERD which includes:

- answer_id (PK)  (int)
- user_id (FK) (int)
- question_id (FK) (int)
- content (text)
- publish_date (date)
- likes_count (int)
- dislikes_count (int)
- picture (**?**)
- is_edited  (boolean)

about the picture column I am not sure which type it should be (URL/File/...), relevant to Questions table to. ( @danitLevi )
I would glad to hear your opinion on this @ifireball.

**Comment by ifireball** [comment]
@idokk1 I would regard something like the picture column as a 2nd phase feature that I would postpone the implementation of.

As you rightly assume, there are various challenges in uploading and storing images. Think if you can initially do without this feature.

**Comment by idokk1** [comment]
OK, thank you.
so for now we will remove the picture column from this table and from question table. (@danitLevi am I right?)

If we want to add columns to an existing table in the future will it be complicated?

**Comment by ifireball** [comment]
> If we want to add columns to an existing table in the future will it be complicated?

No. You'll just need to come up with a default value for the new column for exisiting data if you'll have any - and you're not likely to unless you'll actually launch the app in a production enviromnet ans start having actual users.
