### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by liornoy** [beyond-io/shlifim#183]
@avivz450 Can you please explain to me what this does:
![image](https://user-images.githubusercontent.com/40122521/123725157-450b6200-d896-11eb-8e59-7f0b678e04b5.png)

I mean, what is the definition of the var t if it is written before the for loop, is it some kind of Python magic?

**Comment by avivz450** [comment]
It is a python syntax to make something to each var in the array in one line.
In this case, each var represented as "t" (you could choose another name) and we make all of the letters of each var in the array lower.

**Comment by liornoy** [comment]
ok I get it thanks
