### ISSUE TITLE
Issues regarding the presentation of models on the admin page

### ISSUE THREAD

**Issue by liornoy** [beyond-io/shlifim#27]
Looking at the models through the admin page, I noticed that:

#### 1. Uniting the User and the Profile models to one page on the admin page
There is a different page for viewing users and viewing profiles which in my opinion should be on the same page because the profile model is an extension for the user model, and has one on one relation.

#### 2. How models are being displayed on the admin page: 
In models such 'Book' 'Question', 'Sub-subject', 'Answer' the admin page is showing by default only one column of information, for example for Books it shows only the book's name, but it would be better if it showed the related subject in the same row.

### The solutions:
1. Found [this tutorial](https://simpleisbetterthancomplex.com/tutorial/2016/11/23/how-to-add-user-profile-to-django-admin.html) that shows how to display the Profile information inside the built-in user model page in admin.
2.  Found [this StackOverflow thread](https://stackoverflow.com/questions/163823/can-list-display-in-a-django-modeladmin-display-attributes-of-foreignkey-field) discussing ModelAdmin classes that enable you to add 'list_display' field which customize the way the admin page displays the data of our models. This way the admin page can be more informative. 

Example of the Book model page on the admin page before and after the change 

Before:
![image](https://user-images.githubusercontent.com/40122521/113416668-7b862d80-93ca-11eb-870d-c4da0dd08236.png)

After:
![image](https://user-images.githubusercontent.com/40122521/113416639-6c9f7b00-93ca-11eb-9ba8-ba0e0ec4d3c3.png)

**Comment by idokk1** [comment]
the StackOverflow solution seems pretty simple, I think we should apply it.
