### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by liornoy** [beyond-io/shlifim#28]
1. Change to the new logo.
2. Remove the broken 'flake8' badge and 'version' badge.
3. Add open issues badge.

Assign to @liornoy

**Comment by danitLevi** [comment]
I think we can also remove the "maintained " badge.
We can instead add "pull request" badge as explained in [this link](https://github.com/Naereen/badges)

**Comment by liornoy** [comment]
> I think we can also remove the "maintained " badge.
> We can instead add "pull request" badge as explained in [this link](https://github.com/Naereen/badges)

Good Idea, I updated the PR
