### ISSUE TITLE
Add JS file to 'new_question' page

### ISSUE THREAD

**Issue by avivz450** [beyond-io/shlifim#66]
Need to do it to display certain fields within a Django form based on the data of another selected field within that same form.
For an example :
If the User chose 'Math' in the subject field, he will only see all the sub-subjects that related to math (such as 'Geomtry' and more...)

**Comment by ifireball** [comment]
I would recommend thinking about how to move as much of the functionality to the server-side where we can use our existing code inspection and testing tools to ensure it works. It might require some creative thinking about how to structure the GUI so it works.
