### ISSUE TITLE
Web page contributions User Story

### ISSUE THREAD

**Issue by idokk1** [beyond-io/shlifim#7]
User Story:
As a Shlifim user, 
I want to post a query about my home work
so that other people will respond me and I will find a solution

Use case:
1. The user connects Shlifim website.
2. The user scrolling to the bottom of the page.
3. The user filling the "Author" and "Text" fields with relevant details about his question.
4. The user clicks "Post".
5. The new post is displayed on the website. There is a bold text: **Posted by "Author" at "Current date"**  and below the Text field is displayed.
6. If another user responds to the question, the user will see the responses to his post below it as follows: 
            **Comments:**
            Posted by "author of the response"  at "Current date"
            --Response body--
            (End of messages)

**Comment by danitLevi** [comment]
I think we can delete this for now
