### ISSUE TITLE
Make thumb up/down in display question page work

### ISSUE THREAD

**Issue by liornoy** [beyond-io/shlifim#89]

**Comment by liornoy** [comment]
Pushed the PR. this is how it looks:
![likes_demo](https://user-images.githubusercontent.com/40122521/118116610-2559d080-b3f3-11eb-95ca-0e92adb2df20.PNG)

**Comment by liornoy** [comment]
And for unsigned user it looks like: 
![image](https://user-images.githubusercontent.com/40122521/118140743-521ce080-b411-11eb-9c1a-6a2c57e07a92.png)

**Comment by liornoy** [comment]
![image](https://user-images.githubusercontent.com/40122521/118962065-a6721400-b96d-11eb-86d6-4483645f9245.png)
![image](https://user-images.githubusercontent.com/40122521/118962086-ae31b880-b96d-11eb-985a-2843a584c272.png)

**Comment by idokk1** [comment]
I love the new like/dislike buttons.

**Comment by liornoy** [comment]
![image](https://user-images.githubusercontent.com/40122521/118966251-36b25800-b972-11eb-8f63-a553c7e5c688.png)
![image](https://user-images.githubusercontent.com/40122521/118966295-4467dd80-b972-11eb-8a7e-b0355241ded6.png)
