### ISSUE TITLE
Adding a landing page

### ISSUE THREAD

**Issue by avivz450** [beyond-io/shlifim#9]
User Story:
As a “Shlifim” website user, I want to search or upload questions I may have from homework or assignments I have from school so that I can receive answers, summaries, or sources for my questions.
I'll know I'm done when I managed to find my answer and finish my homework or assignments.

Use Case:
A new user will sign up to the website while a registered user will log in.
Once the user is on the 'Home Page' he will be able to look through the latest questions.
He will be able to search and filter existing questions, add a new question, or add a new answer to an existing question.

For Demo 1 we will create a landing page that includes:
- Our application logo
- A brief explanation of the app
- Coming soon features
- Team members

**Comment by rebeccaTubman** [comment]
#8
